# Site settings
title: "Peter Moskovits"
email: peter.moskovits@gmail.com
description: "Blog from the Silicon Valley"
baseurl: ""
url: http://pmoskovi.github.io
highlighter: rouge

production: true
asseturl: "https://petermoskovits.com"

# Build settings
# markdown: redcarpet
# highlighter: pygments
# permalink: pretty
category-list: [book, websocket, iot, cognitive, ai, saturn, space]
#relative_permalinks: false

kramdown:
  extensions: ["fenced_code_blocks"]
  input: "GFM"
